// FlowGuard - Realistic mock data for demo/development mode

import type { Email, Draft } from "./types"

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString()
}

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString()
}

export const MOCK_INBOX_EMAILS: Email[] = [
  {
    id: "msg-001",
    sender: { name: "David Chen", email: "david.chen@acmelogistics.com" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "RFQ - Dell PowerEdge R760 Servers (Qty 12)",
    bodyPreview: "Hi, we need a quote for 12x Dell PowerEdge R760 servers for our new data center. Please include 3-year ProSupport. See attached specs document.",
    bodyText: "Hi, we need a quote for 12x Dell PowerEdge R760 servers for our new data center. Please include 3-year ProSupport and next business day service. We need the proposal by end of this week. See attached specs document for the full configuration. Best regards, David Chen, IT Director, ACME Logistics",
    receivedDate: hoursAgo(1),
    hasAttachments: true,
    isRead: false,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-001",
  },
  {
    id: "msg-002",
    sender: { name: "Sarah Miller", email: "sarah.m@globalretail.com" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "RE: HPE ProLiant DL380 Gen11 Quote",
    bodyPreview: "Thanks for the proposal. The pricing looks good but we need to discuss the warranty terms. Can we set up a call this week?",
    bodyText: "Thanks for the proposal. The pricing looks good but we need to discuss the warranty terms. The $45,000 total is within our budget but we'd like to explore the 5-year warranty option. Can we set up a call this week? Sarah Miller, Procurement Manager",
    receivedDate: hoursAgo(3),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-002",
  },
  {
    id: "msg-003",
    sender: { name: "Yossi Levi", email: "yossi@techsolutions.co.il" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "Urgent: Aruba CX 6300 Switch Pricing",
    bodyPreview: "We have an urgent project and need Aruba CX 6300 switches. Can you send us a quote by tomorrow morning? Budget is around 200K ILS.",
    bodyText: "We have an urgent government project and need 24x Aruba CX 6300 switches with full licensing. Can you send us a quote by tomorrow morning? Budget is around 200,000 ILS. This is time-sensitive. Yossi Levi, CTO, Tech Solutions Ltd.",
    receivedDate: hoursAgo(6),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-003",
  },
  {
    id: "msg-004",
    sender: { name: "Jennifer Park", email: "j.park@medigroup.com" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "Follow-up: BOM for VMware vSphere Licenses",
    bodyPreview: "Hi, I sent over our requirements last week but haven't received the BOM yet. Our deadline is approaching and we need to finalize the vendor selection.",
    bodyText: "Hi, I sent over our requirements last week but haven't received the BOM yet. Our deadline for vendor selection is Friday. Please find attached our updated requirements. We need the final BOM with all licensing costs. Jennifer Park, IT Procurement",
    receivedDate: hoursAgo(52),
    hasAttachments: true,
    isRead: true,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-004",
  },
  {
    id: "msg-005",
    sender: { name: "IT Newsletter", email: "news@techdigest.com" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "Weekly IT Market Roundup - Server Prices Down 8%",
    bodyPreview: "This week's top stories: Dell announces new PowerEdge lineup, HPE expands GreenLake services...",
    bodyText: "This week's top stories in IT hardware: Dell announces new PowerEdge lineup with AI-optimized configurations. HPE expands GreenLake services. Aruba introduces Wi-Fi 7 access points. Server prices continue downward trend.",
    receivedDate: hoursAgo(12),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-005",
  },
  {
    id: "msg-006",
    sender: { name: "Natan Goldberg", email: "natan@buildright.co.il" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "RE: Cisco Meraki Quote - Need Update",
    bodyPreview: "The quote you sent last month has expired. Can you refresh the pricing? We're ready to proceed with the order. Budget approved.",
    bodyText: "The quote you sent last month has expired. Can you refresh the pricing for the Cisco Meraki MR56 access points (x48) and MS390 switches (x8)? We're ready to proceed with the order as the budget was approved by management. Natan Goldberg, Facilities Manager",
    receivedDate: hoursAgo(30),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-006",
  },
  {
    id: "msg-007",
    sender: { name: "Mark Johnson", email: "mark.j@team-internal.com" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "Team lunch plans for Thursday",
    bodyPreview: "Hey, are you joining us for the team lunch on Thursday? We're thinking about that new sushi place...",
    bodyText: "Hey, are you joining us for the team lunch on Thursday? We're thinking about that new sushi place near the office. Let me know by Wednesday so I can make a reservation. Mark",
    receivedDate: hoursAgo(4),
    hasAttachments: false,
    isRead: true,
    hasReplied: true,
    folder: "inbox",
    conversationId: "conv-007",
  },
  {
    id: "msg-008",
    sender: { name: "Rachel Kim", email: "rachel@fortunemanufacturing.com" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "RFP Response - Network Infrastructure Upgrade",
    bodyPreview: "Attached is our RFP for the complete network infrastructure upgrade. We require proposals from at least 3 vendors. Deadline: next Friday.",
    bodyText: "Dear Sales Team, Attached is our RFP for the complete network infrastructure upgrade project at our manufacturing facility. This includes core switches, access layer, wireless, and security appliances. We require proposals from at least 3 vendors. Submission deadline is next Friday 5PM EST. Please confirm receipt. Rachel Kim, VP Operations",
    receivedDate: hoursAgo(8),
    hasAttachments: true,
    isRead: false,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-008",
  },
  {
    id: "msg-009",
    sender: { name: "Support Ticket", email: "noreply@helpdesk.mycompany.com" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "Ticket #4521 Updated - Customer Delivery Issue",
    bodyPreview: "Ticket #4521 has been updated. Customer reports delivery delay on order ORD-2024-891.",
    bodyText: "Ticket #4521 has been updated by the logistics team. Customer Fortune Manufacturing reports a 3-day delivery delay on order ORD-2024-891 (HPE Storage). Please follow up with the customer. Priority: Medium.",
    receivedDate: hoursAgo(26),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-009",
  },
  {
    id: "msg-010",
    sender: { name: "Amit Patel", email: "amit@cloudnine.io" },
    recipients: [{ name: "Me", email: "sales@mycompany.com" }],
    subject: "Dell APEX Subscription - Price Request",
    bodyPreview: "We are considering Dell APEX as-a-service for our cloud infrastructure. Could you provide pricing for 50TB storage and compute bundles?",
    bodyText: "We are considering Dell APEX as-a-service for our cloud infrastructure buildout. Could you provide pricing for 50TB NVMe storage tier and associated compute bundles? We need both 1-year and 3-year subscription options. Timeline: Q2 deployment. Amit Patel, Cloud Architect, CloudNine Technologies",
    receivedDate: hoursAgo(72),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "inbox",
    conversationId: "conv-010",
  },
]

export const MOCK_DRAFTS: Draft[] = [
  {
    id: "draft-001",
    sender: { name: "Me", email: "sales@mycompany.com" },
    recipients: [{ name: "David Chen", email: "david.chen@acmelogistics.com" }],
    subject: "RE: RFQ - Dell PowerEdge R760 Servers (Qty 12)",
    bodyPreview: "Hi David, Thank you for your inquiry. Please find attached our quotation for the Dell PowerEdge R760 servers...",
    bodyText: "Hi David, Thank you for your inquiry. Please find attached our quotation for the Dell PowerEdge R760 servers as specified. The total comes to...",
    receivedDate: hoursAgo(1),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "drafts",
    lastModified: minutesAgo(45),
    idleMinutes: 45,
    isIntentionalDraft: false,
    hasExternalRecipients: true,
  },
  {
    id: "draft-002",
    sender: { name: "Me", email: "sales@mycompany.com" },
    recipients: [{ name: "Yossi Levi", email: "yossi@techsolutions.co.il" }],
    subject: "RE: Urgent: Aruba CX 6300 Switch Pricing",
    bodyPreview: "Hi Yossi, Here is the pricing breakdown for the Aruba CX 6300 switches...",
    bodyText: "Hi Yossi, Here is the pricing breakdown for the Aruba CX 6300 switches you requested. For 24 units with full licensing:",
    receivedDate: hoursAgo(5),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "drafts",
    lastModified: minutesAgo(120),
    idleMinutes: 120,
    isIntentionalDraft: false,
    hasExternalRecipients: true,
  },
  {
    id: "draft-003",
    sender: { name: "Me", email: "sales@mycompany.com" },
    recipients: [{ name: "Rachel Kim", email: "rachel@fortunemanufacturing.com" }],
    subject: "RE: RFP Response - Network Infrastructure Upgrade",
    bodyPreview: "Dear Rachel, We are pleased to submit our proposal for the network infrastructure upgrade...",
    bodyText: "Dear Rachel, We are pleased to submit our proposal for the network infrastructure upgrade project. Our solution includes: 1. Core Layer: Cisco Catalyst 9500 series...",
    receivedDate: hoursAgo(7),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "drafts",
    lastModified: minutesAgo(35),
    idleMinutes: 35,
    isIntentionalDraft: false,
    hasExternalRecipients: true,
  },
  {
    id: "draft-004",
    sender: { name: "Me", email: "sales@mycompany.com" },
    recipients: [{ name: "Mark Johnson", email: "mark.j@team-internal.com" }],
    subject: "RE: Team lunch plans for Thursday",
    bodyPreview: "Count me in! Sushi sounds great.",
    bodyText: "Count me in! Sushi sounds great. See you Thursday.",
    receivedDate: hoursAgo(3),
    hasAttachments: false,
    isRead: true,
    hasReplied: false,
    folder: "drafts",
    lastModified: minutesAgo(180),
    idleMinutes: 180,
    isIntentionalDraft: false,
    hasExternalRecipients: false,
  },
]

export const MOCK_VIP_CONTACTS = [
  { id: "vip-1", value: "david.chen@acmelogistics.com", type: "email" as const, label: "David Chen - ACME" },
  { id: "vip-2", value: "@globalretail.com", type: "domain" as const, label: "Global Retail" },
  { id: "vip-3", value: "@fortunemanufacturing.com", type: "domain" as const, label: "Fortune Mfg" },
]
